### ISSUE TITLE
gear app no longer propogates arguments

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1131]
[Story](https://www.pivotaltracker.com/story/show/98517242)
Running output/target/pack/bin/gear app -namePrefix test14 -jar output/target/pack/examples/gearpump-examples-kafka-hdfs-pipeline-assembly-0.3.8-SNAPSHOT.jar org.apache.gearpump.streaming.examples.pipeline.KafkaHdfsPipeLine -conf conf/kafka-hdfs-pipeline.conf results in incorrect parsing of arguments

**Comment by kkasravi** [comment]
Here is the output which looks like it truncated the -conf conf/kafka-hdfs-pipeline.conf
```
[ec2-user@ip-10-10-10-236 gearpump]$ output/target/pack/bin/gear app -namePrefix test14 -jar output/target/pack/examples/gearpump-examples-kafka-hdfs-pipeline-assembly-0.3.8-SNAPSHOT.jar org.apache.gearpump.streaming.examples.pipeline.KafkaHdfsPipeLine -conf conf/kafka-hdfs-pipeline.conf
[INFO] [07/06/2015 21:11:25.602] [ClusterConfig$] loading config file application.conf...
[INFO] [07/06/2015 21:11:26.216] [Slf4jLogger] Slf4jLogger started
[INFO] [07/06/2015 21:11:26.344] [Remoting] Starting remoting
[INFO] [07/06/2015 21:11:26.541] [Remoting] Remoting started; listening on addresses :[akka.tcp://client348671170@127.0.0.1:46780]
[INFO] [07/06/2015 21:11:26.579] [Metrics$] Metrics is enabled...,  true
[INFO] [07/06/2015 21:11:26.581] [Metrics$] Metrics reporter is enabled, using akka reporter
[INFO] [07/06/2015 21:11:26.592] [ClientContext] Starting system client348671170
[INFO] [07/06/2015 21:11:26.600] [ClientContext] Creating master proxy Actor[akka://client348671170/user/client348671170#1404100001] for master list: List(HostPort(127.0.0.1,3000))
[ERROR] [07/06/2015 21:11:26.604] [KafkaHdfsPipeLine$] Application Failed
java.lang.Exception: Missing option conf...
	at org.apache.gearpump.cluster.main.ArgumentsParser$$anonfun$parse$2.apply(ArgumentsParser.scala:127)
	at org.apache.gearpump.cluster.main.ArgumentsParser$$anonfun$parse$2.apply(ArgumentsParser.scala:124)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.gearpump.cluster.main.ArgumentsParser$.parse(ArgumentsParser.scala:124)
	at org.apache.gearpump.cluster.main.ArgumentsParser$class.parse(ArgumentsParser.scala:60)
	at org.apache.gearpump.experiments.pipeline.KafkaHdfsPipeLine$.parse(KafkaHdfsPipeLine.scala:111)
	at org.apache.gearpump.experiments.pipeline.KafkaHdfsPipeLine$$anonfun$2.apply(KafkaHdfsPipeLine.scala:152)
	at org.apache.gearpump.experiments.pipeline.KafkaHdfsPipeLine$$anonfun$2.apply(KafkaHdfsPipeLine.scala:152)
	at scala.util.Try$.apply(Try.scala:191)
	at org.apache.gearpump.experiments.pipeline.KafkaHdfsPipeLine$.delayedEndpoint$org$apache$gearpump$experiments$pipeline$KafkaHdfsPipeLine$1(KafkaHdfsPipeLine.scala:151)
	at org.apache.gearpump.experiments.pipeline.KafkaHdfsPipeLine$delayedInit$body.apply(KafkaHdfsPipeLine.scala:111)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.apache.gearpump.experiments.pipeline.KafkaHdfsPipeLine$.main(KafkaHdfsPipeLine.scala:111)
	at org.apache.gearpump.experiments.pipeline.KafkaHdfsPipeLine.main(KafkaHdfsPipeLine.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.apache.gearpump.cluster.main.AppSubmitter$.start(AppSubmitter.scala:73)
	at org.apache.gearpump.cluster.main.AppSubmitter$.delayedEndpoint$org$apache$gearpump$cluster$main$AppSubmitter$1(AppSubmitter.scala:89)
	at org.apache.gearpump.cluster.main.AppSubmitter$delayedInit$body.apply(AppSubmitter.scala:29)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.apache.gearpump.cluster.main.AppSubmitter$.main(AppSubmitter.scala:29)
	at org.apache.gearpump.cluster.main.Gear$.executeCommand(Gear.scala:63)
	at org.apache.gearpump.cluster.main.Gear$.start(Gear.scala:85)
	at org.apache.gearpump.cluster.main.Gear$.delayedEndpoint$org$apache$gearpump$cluster$main$Gear$1(Gear.scala:89)
	at org.apache.gearpump.cluster.main.Gear$delayedInit$body.apply(Gear.scala:25)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.apache.gearpump.cluster.main.Gear$.main(Gear.scala:25)
	at org.apache.gearpump.cluster.main.Gear.main(Gear.scala)
```

**Comment by huafengw** [comment]
Hi Kam, I think its related to issue #995 , you can remove the main class argument, maybe it will work.

**Comment by kkasravi** [comment]
Thanks Huafeng - yes that's what I ended up doing

**Comment by clockfly** [comment]
fixed in PR　https://github.com/intel-hadoop/gearpump/pull/1142
