### ISSUE TITLE
When submit application is failed, the exit code is swallowed

### ISSUE THREAD

**Issue by stanleyxu2005** [intel-hadoop/gearpump#1166]
Step to reproduce:
1. Submit a valid jar via `bin/gear app -jar foo.jar` (The application is running)
2. Submit it again. Expects an error, because the application exists already. But the exit code is always 0.

This will cause restapi handling in dashboard unexpectedly.

```
[ERROR] [07/11/2015 01:09:49.360] [ClientContext] Failed to submit
java.lang.Exception: Application name dag already existed
	at org.apache.gearpump.cluster.master.AppManager$$anonfun$clientMsgHandler$1.applyOrElse(AppManager.scala:96)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.apache.gearpump.cluster.master.AppManager.aroundReceive(AppManager.scala:43)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by stanleyxu2005** [comment]
This issue impacts #1167
