### ISSUE TITLE
KafkaUtilSpec ClassNotFoundException

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#1183]
```
java.lang.NoClassDefFoundError: junit/framework/AssertionFailedError
	at kafka.utils.TestZKUtils$.<init>(TestUtils.scala:796)
	at kafka.utils.TestZKUtils$.<clinit>(TestUtils.scala)
	at org.apache.gearpump.streaming.kafka.util.ZookeeperHarness$class.$init$(ZookeeperHarness.scala:26)
	at org.apache.gearpump.streaming.kafka.lib.KafkaUtilSpec.<init>(KafkaUtilSpec.scala:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:641)
	at sbt.TestRunner.runTest$1(TestFramework.scala:84)
	at sbt.TestRunner.run(TestFramework.scala:94)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
	at sbt.TestFunction.apply(TestFramework.scala:224)
	at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: junit.framework.AssertionFailedError
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at kafka.utils.TestZKUtils$.<init>(TestUtils.scala:796)
	at kafka.utils.TestZKUtils$.<clinit>(TestUtils.scala)
	at org.apache.gearpump.streaming.kafka.util.ZookeeperHarness$class.$init$(ZookeeperHarness.scala:26)
	at org.apache.gearpump.streaming.kafka.lib.KafkaUtilSpec.<init>(KafkaUtilSpec.scala:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:641)
	at sbt.TestRunner.runTest$1(TestFramework.scala:84)
	at sbt.TestRunner.run(TestFramework.scala:94)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
	at sbt.TestFunction.apply(TestFramework.scala:224)
	at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] Could not run test org.apache.gearpump.streaming.kafka.lib.KafkaUtilSpec: java.lang.NoClassDefFoundError: junit/framework/AssertionFailedError
[info] Reading scoverage instrumentation [/home/travis/build/intel-hadoop/gearpump/external/kafka/target/scala-2.11/scoverage-data/scoverage.coverage.xml]
[info] Reading scoverage measurements...
[info] Generating scoverage reports...
[info] Written Cobertura report [/home/travis/build/intel-hadoop/gearpump/external/kafka/target/scala-2.11/coverage-report/cobertura.xml]
[info] Written XML coverage report [/home/travis/build/intel-hadoop/gearpump/external/kafka/target/scala-2.11/scoverage-report/scoverage.xml]
[info] Written HTML coverage report [/home/travis/build/intel-hadoop/gearpump/external/kafka/target/scala-2.11/scoverage-report/index.html]
[info] Coverage reports completed
[info] All done. Coverage was [53.07%]
[info] ScalaTest
[info] Run completed in 2 minutes, 25 seconds.
[info] Total number of tests run: 28
[info] Suites: completed 9, aborted 0
[info] Tests: succeeded 28, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] Error: Total 28, Failed 0, Errors 0, Passed 28
[error] Error during tests:
[error] 	org.apache.gearpump.streaming.kafka.lib.KafkaUtilSpec
```

**Comment by manuzhang** [comment]
able to reproduce the error locally with `sbt test` although not reproducible in intellij.

**Comment by manuzhang** [comment]
This is possibly introduced in by dependency of `dsl`, which could be fixed when dsl's own dependency is cleared.

**Comment by huafengw** [comment]
Fixed.
