### ISSUE TITLE
deserialize java.util.Arraylist cause NPE

### ISSUE THREAD

**Issue by huafengw** [intel-hadoop/gearpump#1191]
We are using Kryo 2.24 for message serialization and deserialization, but it will throws a NPE when encounter java.util.Arraylist
```Caused by: java.lang.NullPointerException
    at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:215)
    at java.util.ArrayList.ensureCapacity(ArrayList.java:199)
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:96)
    at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:22)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679)
    at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) ```

I also found some related issue in Kryo: 
https://github.com/EsotericSoftware/kryo/issues/254

Kryo 3.0 is released and the problem seems is resolved, I'm not sure should we upgrade the Kryo version?

**Comment by huafengw** [comment]
A quick solution:
```
      val kryoSerializer = new KryoSerializer(system.asInstanceOf[ExtendedActorSystem]).serializer
      val kryo = kryoSerializer.kryo
      kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy())
```
