### ISSUE TITLE
File upload for application fails

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1201]
[Story](https://www.pivotaltracker.com/story/show/99756292)
Uploading an application jar fails - looks to be incorrect form-fields are specified

**Comment by kkasravi** [comment]
Here is the log 
```
2015-07-23 22:21:47,544 ERROR ActorSystemImpl: Error during processing of request HttpRequest(POST,http://ip-10-10-10-33.us-west-2.compute.internal:4098/api/v1.0/master/submitapp,List(Accept-Language: en-US, en;q=0.8, Accept-Encoding: gzip, deflate, Referer: http://ip-10-10-10-33.us-west-2.compute.internal:4098/, Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryUBxb3EWTto5jxWSU, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36, Origin: http://ip-10-10-10-33.us-west-2.compute.internal:4098, Content-Length: 32544985, Connection: keep-alive, Host: ip-10-10-10-33.us-west-2.compute.internal:4098),HttpEntity(multipart/form-data; boundary=----WebKitFormBoundaryUBxb3EWTto5jxWSU,------WebKitFormBoundaryUBxb3EWTto5jxWSU^M
Content-Disposition: form-data; name="file"; filename="gearpump-kafka-hbase-pipeline-assembly-0.1-SNAPSHOT.jar"^M
Content-Type: application/java-archive^M
^M
PK^C^D^T^@^H^H^H^@c<97>÷F^@^@^@^@^@^@^@^@^@^@^@^@^T^@^D^@META-INF/MANIFEST.MFþÊ^@^@<9d>Î±
<83>@^L^Fà]ð^]|<81>^\v½­t©P[Aé*Q£^FõîðNèãW^E^]Z<84>Ò-<84>äÿ¿^X^U×d^]<i´¬<95>^LN"ô½h0=^M¤^\ºy    ^Y»<9e>dÐ^P<8e>f^Z^LtXw^Hm<81><96>À°¡<9e>^U}=í<89>¡8Az?'éõ<91>ù^j¨ä<9a>ËíHUz<94>A©^GÑ°k§Bl-<9f>§^?"<96>|<88>ª<9f>*^NÈ1²<82>K<8f>ÖÊ@<8f><8d>@<83>eK{<8a> ^W.­V¬¤|%å^[I$óp;¶^]À|ï^MPK^G^HÎ<94>Æó°^@^@^@<9b>^A^@^@PK^C^D
^@^@^H^@^@c<97>÷F^@^@^@^@^@^@^@^@^@^@^@^@       ^@^@^@META-INF/PK^C^D
^@^@^H^@^@c<97>÷F^@^@^@^@...),HTTP/1.1)
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at org.apache.gearpump.services.MasterService$$anonfun$masterRoute$9$$anonfun$apply$13$$anonfun$apply$16$$anonfun$apply$1.apply$mcV$sp(MasterService.scala:114)
        at org.apache.gearpump.services.MasterService$$anonfun$masterRoute$9$$anonfun$apply$13$$anonfun$apply$16$$anonfun$apply$1.apply(MasterService.scala:114)
        at org.apache.gearpump.services.MasterService$$anonfun$masterRoute$9$$anonfun$apply$13$$anonfun$apply$16$$anonfun$apply$1.apply(MasterService.scala:114)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by stanleyxu2005** [comment]
I suspect your dashboard is out of date. The expected form name of jar is "jar". The form name for a user config is "conf". In your log file, it is "file", so that MasterService does not get the file contents.
