### ISSUE TITLE
KryoException when constructing scala Vector

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#1202]
Running complexdag example could reproduce the following exceptions.
```
ERROR] [07/24/2015 12:04:50.441] [OneForOneStrategy] Class cannot be created (missing no-arg constructor): scala.collection.immutable.Vector
723 com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): scala.collection.immutable.Vector
724         at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1228)
725         at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1049)
726         at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1058)
727         at com.romix.scala.serialization.kryo.ScalaCollectionSerializer.read(ScalaCollectionsSerializer.scala:40)
728         at com.romix.scala.serialization.kryo.ScalaCollectionSerializer.read(ScalaCollectionsSerializer.scala:36)
729         at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:764)
730         at org.apache.gearpump.streaming.MessageSerializer.read(MessageSerializer.scala:34)
731         at org.apache.gearpump.streaming.MessageSerializer.read(MessageSerializer.scala:26)
732         at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:764)
733         at com.romix.akka.serialization.kryo.KryoBasedSerializer.fromBinary(KryoSerializer.scala:394)
734         at akka.serialization.Serializer$class.fromBinary(Serializer.scala:60)
735         at com.romix.akka.serialization.kryo.KryoBasedSerializer.fromBinary(KryoSerializer.scala:368)
736         at org.apache.gearpump.serializer.FastKryoSerializer.deserialize(FastKryoSerializer.scala:74)
737         at org.apache.gearpump.transport.netty.Server$$anonfun$msgHandler$1$$anonfun$applyOrElse$3$$anonfun$apply$1.apply(Server.scala:71)
738         at org.apache.gearpump.transport.netty.Server$$anonfun$msgHandler$1$$anonfun$applyOrElse$3$$anonfun$apply$1.apply(Server.scala:68)
739         at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
740         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
741         at org.apache.gearpump.transport.netty.Server$$anonfun$msgHandler$1$$anonfun$applyOrElse$3.apply(Server.scala:68)
742         at org.apache.gearpump.transport.netty.Server$$anonfun$msgHandler$1$$anonfun$applyOrElse$3.apply(Server.scala:62)
743         at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
744         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
745         at org.apache.gearpump.transport.netty.Server$$anonfun$msgHandler$1.applyOrElse(Server.scala:62)
746         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
747         at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
748         at org.apache.gearpump.transport.netty.Server.aroundReceive(Server.scala:35)
749         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
750         at akka.actor.ActorCell.invoke(ActorCell.scala:487)
751         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
752         at akka.dispatch.Mailbox.run(Mailbox.scala:220)
753         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
754         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
755         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
756         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
757         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by clockfly** [comment]
Need to make sure whether fallback strategy will cause performance issue.

For example, it may rely on exception to decide fallback. And exception is not good for performance.

**Comment by huafengw** [comment]
here is a related issue in Akka-Kryo-Serialization: https://github.com/romix/akka-kryo-serialization/issues/32

**Comment by clockfly** [comment]
UT fails

https://travis-ci.org/intel-hadoop/gearpump/builds/72769561

**Comment by manuzhang** [comment]
the UT failure is related to #1219, which could be caused by multiple versions (2.11.5, 2.11.6) of scala library on the classpath. I'm reverting #1219 in #1220.

**Comment by clockfly** [comment]
Close this for now.
Maybe we can reopen this when issue surface.
