### ISSUE TITLE
Some UT may fail randomly, most because of the expectMsg time out

### ISSUE THREAD

**Issue by huafengw** [intel-hadoop/gearpump#299]

**Comment by huafengw** [comment]
The bug comes from StreamingTestUtil.createEchoForTask

**Comment by clockfly** [comment]
Exception like this:
```
[info] SplitSpec:
[info] - Split should split the text and deliver to next task *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for Message(this,0)
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
[INFO] [01/21/2015 17:00:23.660] [Client$] closing netty client netty-client-HostPort(127.0.0.1,47951)...
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:324)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[info]   at org.apache.gearpump.streaming.examples.kafka.wordcount.SplitSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(SplitSpec.scala:40)
[info]   at org.apache.gearpump.streaming.examples.kafka.wordcount.SplitSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(SplitSpec.scala:39)
[info]   at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[info]   at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[info]   at org.apache.gearpump.streaming.examples.kafka.wordcount.SplitSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SplitSpec.scala:39)
[info]   at org.apache.gearpump.streaming.examples.kafka.wordcount.SplitSpec$$anonfun$1.apply$mcV$sp(SplitSpec.scala:37
```

**Comment by huafengw** [comment]
The root cause is that when the message flush to the EchoTask, there is chance that it has not register itself to the Express, so when message arrives to the Server, it will drop the message.
