### ISSUE TITLE
send messages to TaskActor from StreamingTestUtil could block

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#320]
`testActor ! TaskLocationReady` could block when a TaskActor keeps sending messages to itself without outputting to downstream tasks. 

A possible fix would be to start an actor to send the `TaskLocationReady` message 

```
class LocationReadyActor(target: ActorRef) extends Actor {

  target ! TaskLocationReady

  override def receive: Actor.Receive = {
    case _ =>
  }
}
```

**Comment by manuzhang** [comment]
To reproduce this issue, comment out the line to output message in `wordcount.Split`

```scala
  override def onNext(msg : Message) : Unit = {
    Split.TEXT_TO_SPLIT.lines.foreach { line =>
      line.split(" ").foreach { msg =>
        //output(new Message(msg, System.currentTimeMillis()))
      }
    }
    self ! Message("continue", System.currentTimeMillis())
  }
```

In `SplitSpec`, this will keep the EchoTask from registering to AppMaster and test sending `TaskLocationReady` to TaskActor.

Theaddump from jvisualvm

```
"ScalaTest-run-running-SplitSpec" prio=6 tid=0x0000000003168000 nid=0x2e18 runnable [0x00000000030bc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x00000000c399a4f0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireNanos(AbstractQueuedSynchronizer.java:929)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(AbstractQueuedSynchronizer.java:1245)
  at java.util.concurrent.locks.ReentrantLock.tryLock(ReentrantLock.java:445)
  at akka.testkit.CallingThreadDispatcher.runQueue(CallingThreadDispatcher.scala:275)
  at akka.testkit.CallingThreadDispatcher.dispatch(CallingThreadDispatcher.scala:208)
  at akka.actor.dungeon.Dispatch$class.sendMessage(Dispatch.scala:123)
  at akka.actor.ActorCell.sendMessage(ActorCell.scala:369)
  at akka.actor.Cell$class.sendMessage(ActorCell.scala:290)
  at akka.actor.ActorCell.sendMessage(ActorCell.scala:369)
  at akka.actor.LocalActorRef.$bang(ActorRef.scala:384)
  at org.apache.gearpump.streaming.StreamingTestUtil$.createEchoForTaskActor(StreamingTestUtil.scala:105)
  at org.apache.gearpump.streaming.examples.wordcount.SplitSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SplitSpec.scala:34)
  at org.apache.gearpump.streaming.examples.wordcount.SplitSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SplitSpec.scala:31)
  at org.apache.gearpump.streaming.examples.wordcount.SplitSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SplitSpec.scala:31)
```

and

```
"Split-akka.actor.default-dispatcher-3" prio=6 tid=0x000000000bd49800 nid=0x269c runnable [0x000000000ca5e000]
   java.lang.Thread.State: RUNNABLE
  at java.lang.String.split(String.java:2289)
  at java.lang.String.split(String.java:2355)
  at org.apache.gearpump.streaming.examples.wordcount.Split$$anonfun$onNext$1.apply(Split.scala:33)
  at org.apache.gearpump.streaming.examples.wordcount.Split$$anonfun$onNext$1.apply(Split.scala:32)
  at scala.collection.Iterator$class.foreach(Iterator.scala:743)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
  at org.apache.gearpump.streaming.examples.wordcount.Split.onNext(Split.scala:32)
  at org.apache.gearpump.streaming.task.TaskActor.org$apache$gearpump$streaming$task$TaskActor$$doHandleMessage(TaskActor.scala:184)
  at org.apache.gearpump.streaming.task.TaskActor$$anonfun$stashAndHandleMessages$1.applyOrElse(TaskActor.scala:240)
  at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
  at org.apache.gearpump.streaming.task.TaskActor.aroundReceive(TaskActor.scala:34)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
  at akka.actor.ActorCell.invoke(ActorCell.scala:487)
  at akka.testkit.CallingThreadDispatcher.process$1(CallingThreadDispatcher.scala:251)
  at akka.testkit.CallingThreadDispatcher.runQueue(CallingThreadDispatcher.scala:284)
  at akka.testkit.CallingThreadDispatcher.dispatch(CallingThreadDispatcher.scala:208)
  at akka.actor.dungeon.Dispatch$class.sendMessage(Dispatch.scala:123)
  at akka.actor.ActorCell.sendMessage(ActorCell.scala:369)
  at akka.actor.Cell$class.sendMessage(ActorCell.scala:290)
  at akka.actor.ActorCell.sendMessage(ActorCell.scala:369)
  at akka.actor.LocalActorRef.$bang(ActorRef.scala:384)
  at org.apache.gearpump.streaming.MockAppMaster$$anonfun$receive$1.applyOrElse(StreamingTestUtil.scala:132)
  at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
  at org.apache.gearpump.streaming.MockAppMaster.aroundReceive(StreamingTestUtil.scala:128)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
  at akka.actor.ActorCell.invoke(ActorCell.scala:487)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
  at akka.dispatch.Mailbox.run(Mailbox.scala:220)
  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

   Locked ownable synchronizers:
  - <0x00000000c399a4f0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```

From the [Testing Actor Systems](http://doc.akka.io/docs/akka/snapshot/scala/testing.html) doc,  there are situations when `CallingThreadDispatcher` would block.

**Comment by huafengw** [comment]
In PR #318 , there once used to be a similar situation that the execution thread will block in worker, which maybe the same reason.
