### ISSUE TITLE
TopicOrPartitionUnknown exception thrown by KafkaStorage

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#338]
The cause is that topic for kafka storage is created at runtime and kafka leader has not been elected or metadata not propagated to all brokers.

**Comment by huafengw** [comment]
Also met this exception
[ERROR] [01/22/2015 12:03:04.689] [OneForOneStrategy] Failed to send messages after 3 tries.
kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
        at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
        at kafka.producer.Producer.send(Producer.scala:76)
        at org.apache.gearpump.streaming.kafka.lib.KafkaStorage.append(KafkaStorage.scala:80)
        at org.apache.gearpump.streaming.kafka.lib.KafkaOffsetManager.filter(KafkaOffsetManager.scala:51)
        at org.apache.gearpump.streaming.kafka.KafkaSource.pullHelper$1(KafkaSource.scala:79)
        at org.apache.gearpump.streaming.kafka.KafkaSource.pull(KafkaSource.scala:89)
        at org.apache.gearpump.streaming.examples.stock.Reader.onNext(Reader.scala:30)
        at org.apache.gearpump.streaming.task.TaskActor.org$apache$gearpump$streaming$task$TaskActor$$doHandleMessage(TaskActor.scala:183)
        at org.apache.gearpump.streaming.task.TaskActor$$anonfun$stashAndHandleMessages$1.applyOrElse(TaskActor.scala:240)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at org.apache.gearpump.streaming.task.TaskActor.aroundReceive(TaskActor.scala:34)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by manuzhang** [comment]
a possible fix is to retry checking whether the TopicPartition exists after creation

**Comment by huafengw** [comment]
Is it because of the access to the snapshot topic right after the creation?

**Comment by manuzhang** [comment]
yes, topic path has persisted into zookeeper but leader has not been elected in kafka

**Comment by manuzhang** [comment]
topic creation could still fail. reopen the issue

**Comment by manuzhang** [comment]
the error may be related to https://issues.apache.org/jira/browse/KAFKA-1738. I will try out the latest kafka trunk

**Comment by clockfly** [comment]
Confirmed this is due to  https://issues.apache.org/jira/browse/KAFKA-1738
