### ISSUE TITLE
[UT]lots of netty client ClosedChannelException in UT logs

### ISSUE THREAD

**Issue by manuzhang** [intel-hadoop/gearpump#388]
The exception is thrown when a netty client closes its channel. It sends a downstream event but the server is already down. Here are the details.

```
INFO] [02/03/2015 09:24:49.181] [Client$] closing netty client netty-client-HostPort(192.168.1.74,48598)...
[ERROR] [02/03/2015 09:24:49.182] [Client$] failed to send requests to /192.168.1.74:48598
java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:405)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:373)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:58)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.jboss.netty.channel.Channels.close(Channels.java:812)
        at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:197)
        at org.apache.gearpump.transport.netty.Client.org$apache$gearpump$transport$netty$Client$$close(Client.scala:138)
        at org.apache.gearpump.transport.netty.Client.postStop(Client.scala:145)
        at akka.actor.Actor$class.aroundPostStop(Actor.scala:475)
        at org.apache.gearpump.transport.netty.Client.aroundPostStop(Client.scala:36)
        at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)
        at akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)
        at akka.actor.ActorCell.terminate(ActorCell.scala:369)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[ERROR] [02/03/2015 09:24:49.185] [Client$] failed to send requests to /192.168.1.74:48598
java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:405)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:373)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:58)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.jboss.netty.channel.Channels.close(Channels.java:812)
        at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:197)
        at org.apache.gearpump.transport.netty.Client.org$apache$gearpump$transport$netty$Client$$close(Client.scala:138)
        at org.apache.gearpump.transport.netty.Client.postStop(Client.scala:145)
        at akka.actor.Actor$class.aroundPostStop(Actor.scala:475)
        at org.apache.gearpump.transport.netty.Client.aroundPostStop(Client.scala:36)
        at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)
        at akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)
        at akka.actor.ActorCell.terminate(ActorCell.scala:369)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
```

It seems to be a long standing [netty issue](https://issues.jboss.org/browse/NETTY-412).

**Comment by clockfly** [comment]
This is only related with UT test log, it doesn't impact the function of the cluster.

**Comment by manuzhang** [comment]
this is **not** only related with UT test log. It's reproducible by running WordCount on 2-node cluster. Then check the executor logs on both nodes and one of them would say the above.

**Comment by clockfly** [comment]
Here are my questions:

1. How frequent this happen? Can you reproduce this everytime?
2. What is the impact of this issue? 
3. What is the suggested workaround if the upstream doesn't fix this?

**Comment by manuzhang** [comment]
1. Not reproducible every time. Actually, I haven't seen it for recent runs. 
2. The impact is users will see some errors and exceptions in the log, which would suggest bugs in the program to them. 
3. one possible solution is to catch the exception on `channel.close()`

```scala
  private def close() {
    LOG.info(s"closing netty client $name...")
    if (null != channel) {
      channel.close()
      channel = null
    }
    batch.clear()
  }
```

**Comment by clockfly** [comment]
@manuzhang 

By looking at the code, the close() is called in postStop of actor
```
// from Client Actor
  override def postStop() = {
    close()
  }
```

I don't know what will happen when exception is thrown out from this call.
As the Client Actor was planning to shutdown itself, so catch this error by logging should have no risk. 
so please make a quick PR for this,

I suggest we could log like this:

//use WARN log level to indicate this error has been considered.
LOG.warn("exception found when trying to close netty connection, ${ex.msg}")

**Comment by manuzhang** [comment]
sorry, I missed that the exception is caught by `ClientErrorHandler`

```scala
 class ClientErrorHandler(name: String) extends SimpleChannelUpstreamHandler {

    override def exceptionCaught(ctx: ChannelHandlerContext, event: ExceptionEvent) {
      event.getCause match {
        case ex : ConnectException => Unit
        case ex => LOG.error("Connection failed " + name, ex)
      }
    }
  }
```

the exception I posted above is actually part of the error log. How about adding a warning for `ClosedChannelException` ?

```scala
    override def exceptionCaught(ctx: ChannelHandlerContext, event: ExceptionEvent) {
      event.getCause match {
        case ex : ConnectException => Unit
        case ex: ClosedChannelException =>
          LOG.warn("exception found when trying to close netty connection", ex.getMessage)
        case ex => LOG.error("Connection failed " + name, ex)
      }
    }
```

Meanwhile, the issue is tracked at https://github.com/netty/netty/issues/724 and fixed in netty 4
