### ISSUE TITLE
For test code, the ClockService will throw excepton when the DAG is not defined

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#468]
```
java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1221)
	at java.util.TreeMap.firstKey(TreeMap.java:285)
	at java.util.TreeSet.first(TreeSet.java:394)
	at org.apache.gearpump.streaming.appmaster.ClockService.org$apache$gearpump$streaming$appmaster$ClockService$$minClock(ClockService.scala:118)
	at org.apache.gearpump.streaming.appmaster.ClockService$$anonfun$clockService$1.applyOrElse(ClockService.scala:114)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.apache.gearpump.streaming.appmaster.ClockService.aroundReceive(ClockService.scala:41)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`
```

**Comment by clockfly** [comment]
fixed.
