### ISSUE TITLE
Unittest KafkaStreamProducerSpec fail

### ISSUE THREAD

**Issue by clockfly** [intel-hadoop/gearpump#659]
```
[0m[[0minfo[0m] [0m[32mKafkaStreamProducerSpec:[0m[0m
[0m[[0minfo[0m] [0m[31m- KafkaStreamProducer should pull messages from kafka *** FAILED ***[0m[0m
[0m[[0minfo[0m] [0m[31m  java.lang.RuntimeException: broker info not found for leader 0[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.apache.gearpump.streaming.kafka.lib.KafkaUtil$.getBroker(KafkaUtil.scala:40)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.apache.gearpump.streaming.kafka.lib.KafkaConsumer$.apply(KafkaConsumer.scala:31)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.apache.gearpump.streaming.kafka.lib.FetchThread$$anonfun$1.apply(FetchThread.scala:34)[0m[0m
[0m[[0minfo[0m] [0m[31m  at org.apache.gearpump.streaming.kafka.lib.FetchThread$$anonfun$1.apply(FetchThread.scala:33)[0m[0m
[0m[[0minfo[0m] [0m[31m  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)[0m[0m
[0m[[0minfo[0m] [0m[31m  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)[0m[0m
[0m[[0minfo[0m] [0m[31m  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)[0m[0m
[0m[[0minfo[0m] [0m[31m  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)[0m[0m
[0m[[0minfo[0m] [0m[31m  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)[0m[0m
[0m[[0minfo[0m] [0m[31m  at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)[0m[0m
[0m[[0minfo[0m] [0m[31m  ...[0m[0m
```

**Comment by clockfly** [comment]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/55586382/log.txt

**Comment by manuzhang** [comment]
what's the context for this spec failure ? It fails on s3 ?

**Comment by clockfly** [comment]
Seems random.

close this.

**Comment by clockfly** [comment]
Happeninng again:

```
[info] KafkaStreamProducerSpec:
[info] - KafkaStreamProducer should pull messages from kafka *** FAILED ***
[info]   kafka.admin.AdminOperationException: replication factor: 1 larger than available brokers: 0
[info]   at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:70)
[info]   at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:171)
[info]   at kafka.utils.TestUtils$.createTopic(TestUtils.scala:179)
[info]   at org.apache.gearpump.streaming.kafka.util.KafkaServerHarness$class.createTopicUntilLeaderIsElected(KafkaServerHarness.scala:83)
[info]   at org.apache.gearpump.streaming.examples.kafka.KafkaStreamProducerSpec.createTopicUntilLeaderIsElected(KafkaStreamProducerSpec.scala:44)
[info]   at org.apache.gearpump.streaming.examples.kafka.KafkaStreamProducerSpec$$anonfun$1.apply$mcV$sp(KafkaStreamProducerSpec.scala:71)
[info]   at org.apache.gearpump.streaming.examples.kafka.KafkaStreamProducerSpec$$anonfun$1.apply(KafkaStreamProducerSpec.scala:66)
[info]   at org.apache.gearpump.streaming.examples.kafka.KafkaStreamProducerSpec$$anonfun$1.apply(KafkaStreamProducerSpec.scala:66)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   ...
```
https://api.travis-ci.org/jobs/56834733/log.txt?deansi=true

**Comment by clockfly** [comment]
Another failure noticed.

https://travis-ci.org/intel-hadoop/gearpump/builds/56995207

gearpump-example-kafka test failed.

```
java.lang.NoClassDefFoundError: Could not initialize class kafka.utils.TestZKUtils$
        at org.apache.gearpump.streaming.kafka.util.ZookeeperHarness$class.$init$(ZookeeperHarness.scala:26)
        at org.apache.gearpump.streaming.examples.kafka.KafkaStreamProcessorSpec.<init>(KafkaStreamProcessorSpec.scala:39)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:379)
        at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:641)
        at sbt.TestRunner.runTest$1(TestFramework.scala:84)
        at sbt.TestRunner.run(TestFramework.scala:94)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
        at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
        at sbt.TestFunction.apply(TestFramework.scala:224)
        at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
        at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
        at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] Could not run test org.apache.gearpump.streaming.examples.kafka.KafkaStreamProcessorSpec: java.lang.NoClassDefFoundError: 
```

**Comment by kkasravi** [comment]
It may be worthwhile to consider doing DI on KafkaStreamProducer so that KafkaSource is a service injected into the class. This would allow testing of KafkaStreamProducer without actually starting kafka and zookeeper. I think starting these servers correctly as part of the KafkaStreamProducerSpec test can be very challenging. I would be happy to take a pass on it and have @manuzhang and @clockfly review.
Thanks Kam

**Comment by manuzhang** [comment]
Hi Kam. KafkaStreamProducerSpec is an integration test, where kafka and zookeeper are supposed to be launched. This is to save us time for setting up a kafka cluster to verify the KafkaStreamProducer and KafkaSource is actually working.

**Comment by manuzhang** [comment]
I tried clearing my sbt cache (`rm -rf ~/.ivy2/cache/*) and running KafkaStreamProducerSpec but could not reproduce the failures.

**Comment by kkasravi** [comment]
Hi TIanlun - i can see value in actually launching these servers but can also see value in injecting a fake KafkaSource into KafkaStreamProducer for unit testing of KafkaStreamProducer. Depends what your testing. I know bringing up multiple servers and insuring they always have the same state can be very challenging.

**Comment by manuzhang** [comment]
Yes. We could have two directories "integration" and "unit" for these two purposes respectively (that's how kafka tests its own functions). The problem of unit testing KafkaStreamProducer is general for all that conforming to Task interface. I'm +1 to make it more testable but that may involve the whole interface design.

**Comment by kkasravi** [comment]
Ok, I have a KafkaProducer under pipeline, maybe I'll take a pass on that since it's basically what you wrote. Thanks

**Comment by clockfly** [comment]
Same error

https://travis-ci.org/intel-hadoop/gearpump/builds/60208530

**Comment by manuzhang** [comment]
master build failed because of this. Maybe I should remove the spec for now.
