### ISSUE TITLE
ExecutorManagerSpec fails on NPE

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#863]
```
[info] - should report timeout to taskManager *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at org.apache.gearpump.streaming.appmaster.ExecutorManagerSpec.org$apache$gearpump$streaming$appmaster$ExecutorManagerSpec$$startExecutorSystems(ExecutorManagerSpec.scala:73)
[info]   at org.apache.gearpump.streaming.appmaster.ExecutorManagerSpec$$anonfun$1.apply$mcV$sp(ExecutorManagerSpec.scala:88)
[info]   at org.apache.gearpump.streaming.appmaster.ExecutorManagerSpec$$anonfun$1.apply(ExecutorManagerSpec.scala:86)
[info]   at org.apache.gearpump.streaming.appmaster.ExecutorManagerSpec$$anonfun$1.apply(ExecutorManagerSpec.scala:86)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
[info]   ...
```

**Comment by manuzhang** [comment]
ExecutorManagerSpec on master failed with the following info
```
[info] - should report timeout to taskManager *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout 1 second expired:
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.poll$1(TestKit.scala:227)
[info]   at akka.testkit.TestKitBase$class.awaitCond(TestKit.scala:233)
[info]   at akka.testkit.TestKit.awaitCond(TestKit.scala:718)
[info]   at akka.testkit.TestKitBase$class.$init$(TestKit.scala:128)
[info]   at akka.testkit.TestKit.<init>(TestKit.scala:718)
[info]   at akka.testkit.TestProbe.<init>(TestKit.scala:783)
[info]   at akka.testkit.TestProbe$.apply(TestKit.scala:815)
[info]   at org.apache.gearpump.streaming.appmaster.ExecutorManagerSpec.org$apache$gearpump$streaming$appmaster$ExecutorManagerSpec$$startExecutorSystems(ExecutorManagerSpec.scala:51)
[info]   at org.apache.gearpump.streaming.appmaster.ExecutorManagerSpec$$anonfun$1.apply$mcV$sp(ExecutorManagerSpec.scala:91)
[info]   ...
```

**Comment by kkasravi** [comment]
hmmm, ok maybe it's resolved. Closing. Thanks @manuzhang !
