### ISSUE TITLE
LOG in TimeoutScheduler causes JVM exit

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#959]
[Story](https://www.pivotaltracker.com/story/show/95555240)
This happens when running sbt under JDK8

**Comment by kkasravi** [comment]
Stack trace

[ERROR] [05/27/2015 11:34:14.456] [OneForOneStrategy] exception during creation
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
	at akka.actor.ActorCell.create(ActorCell.scala:596)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at akka.util.Reflect$.instantiate(Reflect.scala:66)
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
	at akka.actor.Props.newActor(Props.scala:252)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	... 9 more
Caused by: java.lang.AbstractMethodError: org.apache.gearpump.cluster.worker.Worker.org$apache$gearpump$util$TimeOutScheduler$_setter_$org$apache$gearpump$util$TimeOutScheduler$$log_$eq(Lorg/slf4j/Logger;)V
	at org.apache.gearpump.util.TimeOutScheduler$class.$init$(TimeOutScheduler.scala:30)
	at org.apache.gearpump.cluster.worker.Worker.<init>(Worker.scala:53)
	... 18 more
[INFO] [05/27/2015 11:34:14.458] [Master] master path is akka.tcp://system@127.0.0.1:64003/user/master
Uncaught error from thread [[ERROR] [05/27/2015 11:34:14.500] [ActorSystemImpl] Uncaught error from thread [system-akka.actor.default-dispatcher-16] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.AbstractMethodError: org.apache.gearpump.cluster.master.AppManager.org$apache$gearpump$util$TimeOutScheduler$_setter_$org$apache$gearpump$util$TimeOutScheduler$$log_$eq(Lorg/slf4j/Logger;)V
	at org.apache.gearpump.util.TimeOutScheduler$class.$init$(TimeOutScheduler.scala:30)
	at org.apache.gearpump.cluster.master.AppManager.<init>(AppManager.scala:46)
	at org.apache.gearpump.cluster.master.Master$$anonfun$preStart$1.apply(Master.scala:212)
	at org.apache.gearpump.cluster.master.Master$$anonfun$preStart$1.apply(Master.scala:212)
	at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:343)
	at akka.actor.Props.newActor(Props.scala:252)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
system-akka.actor.default-dispatcher-16] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[system]
java.lang.AbstractMethodError: org.apache.gearpump.cluster.master.AppManager.org$apache$gearpump$util$TimeOutScheduler$_setter_$org$apache$gearpump$util$TimeOutScheduler$$log_$eq(Lorg/slf4j/Logger;)V
	at org.apache.gearpump.util.TimeOutScheduler$class.$init$(TimeOutScheduler.scala:30)
	at org.apache.gearpump.cluster.master.AppManager.<init>(AppManager.scala:46)
	at org.apache.gearpump.cluster.master.Master$$anonfun$preStart$1.apply(Master.scala:212)
	at org.apache.gearpump.cluster.master.Master$$anonfun$preStart$1.apply(Master.scala:212)
	at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:343)
	at akka.actor.Props.newActor(Props.scala:252)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by manuzhang** [comment]
Hi Kam,

This may not be a problem with sbt under JDK8.
Huafeng and I have come across this error before (I use JDK7). It went away after I ran `sbt clean` and then built again.
